---
- name: Another network playbook example
  # The line below uses regex to parse the inventory file
  hosts: ~^arista
  gather_facts: no



  tasks:
  - name: Harvest Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'


  - name: Push to the local system -- by special tag request only
    copy: 
     # use the to_no_json filter to display pretty json output
      content: "{{ ansible_facts | to_nice_json }}"
      dest: "/home/student/mycode/{{ inventory_hostname }}.txt"

    tags:
      - never
      - grabfacts


    # Precheck conditional number of interfaces
  - fail:
      msg: "FAIL. Network device lacks the correct number of interfaces!"
    when: ansible_facts.net_interfaces|length != 13


    # Firmware precheck on correct major and minor versions
  - fail:
      msg: "FAIL.  Network device is running wrong firmware."
    when: "'4.17' not in ansible_facts.net_version"
