---
- name: How to print with debug
  hosts: localhost
  gather_facts: no

  vars: 
    vendorip: '192.168.22.55'

  tasks:
    - name: Print out to the screen
      debug:
        msg: "Welcome to Ansibibble!"

    - name: Print a message variable
      debug: 
        msg: "The vendor IP is: {{ vendorip }}"
        # note that recall within the msg parameter requires mustache/curly brackets

    - name: Print just a variable
      debug:
        var: vendorip
        # note that recall within var parameter does NOT require mustache/curly brackets
 
    - name: Print only with verbosity
      debug: 
        var: vendorip
        verbosity: 3
